### ISSUE TITLE
Module status

### ISSUE THREAD

**Issue by Sturgelose** [gaaiatinc/hapi-openid-connect#1]
Hi!

Just to know, is this module dead or is there any way to help on it?

**Comment by aliismael** [comment]
Hi Erik,

The module is being heavily developed and completed.  I am confident I can
publish version 1.0.1 of it in less than 10 days.

When I publish it, it will have a complete sample app, which uses mongo
database for persistence.

I will send you a direct email when I publish the completed version, and I
will actually be indebted to you if you can test the sample app and give me
feedback on it.

Yours truly,
Ali

Yours truly,

Ali Ismael, Ph.D.
Gaaiat, Inc

**Comment by Sturgelose** [comment]
Hi,

Thanks a lot! I was taking a look on it because it would interesting to use it in a project where we need OpenIDConnect authentication/authorization. So, aside of your example, I'd be glad to use it in a real project (for my master thesis and eventually deployed in production, I hope), and give you more feedback :)

**Comment by aliismael** [comment]
Hi Erik,

I just pushed the first version of the hapi-openid-connect plugin (version
1.0.x).  This version is a complete implementation of the
authorization_code, password, and refresh_token grant_type.  Also, this
version has a sample application which uses mongodb for persistence, but I
still need to include documentation for it.

I will update the documentation in the next couple of days, but feel free
to check the sample application as an indirect documentation.

Yours truly,
Ali

Yours truly,

Ali Ismael, Ph.D.
Gaaiat, Inc

**Comment by aliismael** [comment]
I have just published the stable version of the hapi-openid-connect with a fully functional sample application (built on the valde-hapi stack).  

Please let me know if you need help with it.
