### ISSUE TITLE
Steam / OpenID 2.0

### ISSUE THREAD

**Issue by ghost** [gaaiatinc/hapi-openid-connect#3]
Hi,

I was looking at the following issue https://github.com/hapijs/bell/issues/164 and saw you released the code for openid-connect, but it doesn't seem like you have implemented OpenID 2.0 for steam. Does this actually work for steam? I can't find any references for realm in the project since steam requires realm in the url such as openid.realm="http://...".

Thanks.

**Comment by ghost** [comment]
Nevermind just ended up implementing it myself since it was easier than I though.

**Comment by lenovouser** [comment]
@dauphin327 do you mind sharing or open sourcing the code? I need this too 👍

**Comment by aliismael** [comment]
Sorry but we had no intention to support OpenID 2.0 as we stated in the documentation.  This module is an implementation of OpenID-Connect spec only.

**Comment by lenovouser** [comment]
@aliismael I know, but @dauphin327 said he implemented it himself and I was interested in his implementation because Steam only supports OpenID 2.0
